/**
 * AUTO-GENERATED by `npm run gen:reference` from docs/reference/missions/*.md's
 * "Common mistakes" / "Key insight" sections — do not hand-edit. Those
 * markdown files are the single source of truth; edit them and rerun the
 * script instead of editing this file directly.
 */
import type { Mission } from './missions';

export const teachingNotes: Partial<Record<Mission['id'], string>> = {
  'm1-1': "Common mistake: Missing the USA filter. Terminal restored. Filtering BillingCountry before sorting is what kept ROGUE.exe's junk rows out of the ranking — sort first and you'd be ranking noise instead of real invoices.",
  'm1-2': "Common mistake: Missing DISTINCT. Map restored. DISTINCT collapsed ROGUE.exe's duplicate entries back down to one row per country — 24 real markets, no padding.",
  'm1-3': "Common mistake: Missing the % wildcards. Search terminal fixed. LOWER() normalizes case before the pattern match runs, so ROGUE.exe's case trick can't hide a match just by capitalizing it differently.",
  'm1-4': "Common mistake: Missing the price filter. Terminal restored. Dividing by 60000.0 keeps this a real fraction instead of integer-dividing it away — that decimal is what exposes tracks charging a premium price for barely any runtime.",
  'm1-5': "Common mistake: Incomplete range. Gap swept. BETWEEN 15 AND 20 is shorthand for Total >= 15 AND Total <= 20, but written as one inclusive range instead of two conditions to keep straight — exactly the band a scan built around round thresholds would have…",
  'm1-6': "Common mistake: Missing one of the three markets. Shortlist pulled. WHERE BillingCountry IN (...) is exactly WHERE BillingCountry = 'Chile' OR BillingCountry = 'Hungary' OR BillingCountry = 'Norway', just written as one list instead of a chain of ORs that gets uglier ev…",
  'm2-1': "Common mistake: Joined to another table. Scoreboard restored. Every Invoice row is already a completed sale, so summing Total per country gives a clean scorecard — joining to invoice lines would have multiplied each sale by its line count, which is exactly the…",
  'm2-2': "Common mistake: Missing HAVING. Filter rewired. WHERE runs before grouping, so it can't see a summed total that doesn't exist yet — HAVING runs after GROUP BY, which is exactly why it's the only clause that can filter on SUM(Total).",
  'm2-3': "Common mistake: Missing DISTINCT. Corruption isolated. All three numbers pull from the same table, but only DISTINCT collapses repeat buyers to one each — the gap between 412 and 59 is exactly the shape of overcounting ROGUE.exe relies on elsewhere.",
  'm2-4': "Common mistake: Missing MIN or MAX. Bounds certified. MIN and MAX are the same aggregation family as SUM, COUNT, and AVG — they just answer \"smallest\" and \"largest\" instead of \"total\" or \"how many,\" and now any invoice outside $0.99–$25.86 is an instant re…",
  'm3-1': "Common mistake: Missing JOIN. Relay reconnected. The CustomerId foreign key is the wire ROGUE.exe cut — joining on it turns anonymous invoice rows back into a named follow-up list the sales lead can actually use.",
  'm3-2': "Common mistake: Missing JOIN. Line items restored. InvoiceLine is the join table connecting a specific invoice to the specific tracks bought on it — without it, an invoice is just a total with no receipt behind it.",
  'm3-3': "Common mistake: Missing GROUP BY. Genre scorecard rebuilt. Revenue only exists at the InvoiceLine grain — joining through Track to Genre attaches every real sale to its genre without inventing numbers Track never had.",
  'm3-4': "Common mistake: JOIN instead of LEFT JOIN. Reactivation list restored. An INNER JOIN drops any customer with zero matching invoices — exactly the people this list needs.",
  'm4-1': "Common mistake: Missing the AVG subquery. Triage restored. The subquery computes one number — the real average — before the outer WHERE ever runs, so every invoice gets compared to the same real bar instead of nothing at all.",
  'm4-2': "Common mistake: Missing LIMIT 10. Leaderboard staged. A CTE computes LifetimeRevenue exactly once, so every join and sort downstream reads the same staged number instead of ROGUE.exe recomputing (and drifting) it on the fly.",
  'm4-3': "Common mistake: Missing the $10 filter. Workbench proven. The temp table exists only for this run — it is gone the moment the terminal resets — but while it is alive, it queries exactly like a real table, which is the whole point of staging work before the fin…",
  'm5-1': "Common mistake: Missing strftime on InvoiceDate. Gears unstuck. strftime('%Y', ...) reads the real year out of every invoice date, so revenue lines up on an actual five-year timeline instead of the one jammed year ROGUE.exe was stalling on.",
  'm5-2': "Common mistake: Grouped by month without year. Dial freed. %Y-%m keeps months sortable across years instead of colliding every January — that is what let the real top-10 months surface instead of the one frozen reading ROGUE.exe was stuck on.",
  'm5-3': "Common mistake: Missing strftime('%J', ...). Vault age confirmed: 1,816 days, not \"just started.\" strftime('%J', ...) turns each date into a comparable day-number, and subtracting two of them is exactly how you'd measure any duration — signup-to-churn, order-to-del…",
  'm6-1': "Common mistake: Missing ELSE. Switch rebuilt. CASE routes every invoice into exactly one labeled bin by testing conditions in order, top to bottom — the same three-way sort ROGUE.exe had jammed into a single lane.",
  'm6-2': "Common mistake: Missing GROUP BY. Output locked to whole units. CAST(...",
  'm7-1': "Common mistake: UNION ALL instead of UNION. Vault deduplicated. UNION collapses any country appearing on both sides down to one row — UNION ALL would have kept every one of ROGUE.exe's duplicates intact.",
  'm7-2': "Common mistake: Missing LIMIT 5. View restored. CountryRevenue now exists as a saved query for this run — nobody has to rewrite the GROUP BY from scratch, which is exactly the shared asset ROGUE.exe deleted.",
  'm7-3': "Common mistake: UNION instead of UNION ALL. 471 mentions: 59 customer rows plus 412 invoice rows, every one kept. That's a completely different question from the 24 distinct markets UNION found earlier — UNION ALL is the tool whenever the count of duplicates is it…",
  'm7-4': "Common mistake: UNION instead of INTERSECT. 21 markets confirmed active in both directions. INTERSECT is stricter than UNION — UNION would have combined both lists regardless of overlap, but INTERSECT only keeps what's genuinely true on both sides at once, which i…",
  'm7-5': "Common mistake: EXCEPT sides reversed. Three markets gone quiet in 2011: Australia, Chile, Sweden. Notice EXCEPT isn't symmetric like UNION or INTERSECT — \"customer countries EXCEPT 2011 billing countries\" and \"2011 billing countries EXCEPT customer countries…",
  'm8-1': "Common mistake: Missing DISTINCT. Corruption purged. ROGUE.exe's 412 was invoice rows wearing a trenchcoat — DISTINCT CustomerId strips the disguise and returns 59 actual people.",
  'm8-2': "Common mistake: Missing the 2010 filter. Claim rescoped. USA still leads — but only inside one real year, not ROGUE.exe's lifetime total stretched to look current.",
  'm8-3': "Common mistake: Missing HAVING. Cut list exposed. Revenue alone put eleven genres on ROGUE.exe's chopping block — but this table has no margin, no licensing cost, and no customer-retention data in it.",
  'm9-1': "Common mistake: Missing the MAX(year) subquery. Question framed. The subquery pulls whatever year is actually most recent instead of a guess baked into the query — the same discipline that keeps a real analyst from running on a stale assumption.",
  'm9-2': "Common mistake: Missing DISTINCT. Verdict closed. USA leads on both revenue and reach — real signal, not a guess — but it's still a closed-year rearview mirror, not a promise about what happens next.",
};
